---
# main tasks file for the mongo-baking role

- name: Adding the mongodb repository
  copy:
    src: ./mongodb.repo
    dest: /etc/yum.repos.d/
    mode: 0644

- name: Adding the extra repository to install pip
  yum:
    name: epel-release
    state: present

- name: Install MongoDB and other essential programs
  yum:
    name:
      - mongodb-org
      - python-pip
      - policycoreutils
      - policycoreutils-python
      - initscripts
      - jq
    state: present

- name: Install pymongo
  pip:
    name:
      - pymongo
      - pyopenssl
      - yq
    state: present

- name: Install the executable scripts
  copy:
    src: ./files/bin/
    dest: /usr/bin/
    group: root
    owner: root
    mode: 0755

- name: Disable transparent huge pages
  include_tasks: thp-disable.yml

- name: Copy the initial configuration file
  copy:
    src: mongod.conf
    dest: /etc/mongod.conf
    mode: 0644
    group: mongod
    owner: mongod

- name: Assure mongod is started
  systemd:
    name: mongod
    enabled: true
    state: started
