---
# main tasks file for the mongo-baking role

- name: Install the necessary packages
  include_tasks: packages.yml

- name: Install the executable scripts
  copy:
    src: ./files/bin/
    dest: /usr/bin/
    group: root
    owner: root
    mode: 0755

- name: Back up the original configuration file
  shell: cat /etc/mongod.conf > /etc/mongod.original.conf
  args:
    creates: /etc/mongod.original.conf

- name: Copy the initial configuration file
  template:
    src: mongod.conf.j2
    dest: /etc/mongod.conf
    mode: 0644
    group: mongod
    owner: mongod

- name: Set up the permissions
  include_tasks: permissions.yml

- name: Set up the services
  include_tasks: services.yml
