---
# tasks file for baker

- name: Adding the mongodb repository
  copy:
    src: './mongodb.repo'
    dest: '/etc/yum.repos.d/'
    mode: 0644

- name: Adding the extra repository to install pip
  yum:
    name: epel-release
    state: present

- name: Install MongoDB and other essential programs
  yum:
    name:
      - mongodb-org
      - python-pip
      - jq
      - policycoreutils-python
    state: present

- name: Install pymongo
  pip:
    name:
      - pymongo
      - pyopenssl
    state: present

- name: Disable transparent huge pages
  block:
    - name: Copy the disabler script
      copy:
        src: 'disable-thp.sh'
        dest: '/bin/disable-thp.sh'
        mode: 0755

    - name: Copy the service file
      copy:
        src: 'disable-thp.service'
        dest: '/etc/systemd/system/disable-thp.service'
        mode: 0755

    - name: Enable the service
      service:
        name: disable-thp
        state: started
        enabled: true

- name: Copy the initial configuration file
  copy:
    src: 'mongod.conf'
    dest: '/etc/mongod.conf'
    mode: 0644
    group: mongod
    owner: mongod

- name: Assure mongod is started
  service:
    name: mongod
    enabled: true
    state: started
