---
- name: Prepare
  hosts: all
  tasks:
    # - name: Create docker network(s)
    #   docker_network:
    #     name: "{{ molecule_yml.platforms | molecule_get_docker_networks | first }}"
    #     state: present
    #   register: dockerizado

    - name: Bake the container
      include_role:
        name: mongo-baking
