---
dependency:
  name: galaxy

driver:
  name: docker

lint:
  name: yamllint

platforms:
  - name: mongodb-deployment-instance
    image: centos/systemd
    override_command: false
    privileged: true
    capabilities:
      - SYS_ADMIN
    security_opts:
      - seccomp=unconfined
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

provisioner:
  name: ansible
  lint:
    name: ansible-lint
  options:
    v: true
  config_options:
    defaults:
      stdout_callback: debug

scenario:
  name: default

verifier:
  name: testinfra
  lint:
    name: flake8
