---
- name: Assert the db folders exist with the proper permission
  file:
    path: "{{ dbpath }}/{{ item }}"
    recurse: true
    state: directory
    owner: mongod
    group: mongod
    mode: 0755
  with_items:
    - data
    - log
    - run
    - tmp
  changed_when: false

- name: SELinux policy for the no-auth TCP port
  shell: |
    port={{ port_noauth }}
    type_now=$(semanage port -l | grep tcp | grep "$port" | awk -F' ' '{print $1}')
    type_new=mongod_port_t

    if [ $type_now != $type_new ]; then
      semanage port -a -t $type_new -p tcp $port
      echo 'Proper SELinux policies set'
    fi

  register: selinux_port
  changed_when: selinux_port.stdout.find('Proper SELinux policies set') != -1

- name: Set proper SELinux policies
  shell: |
    path='{{ dbpath }}/{{ item.path }}'
    type_now=$(ls -dZ "$path" | awk '{print $4}' | awk -F':' '{print $3}')
    type_new={{ item.type }}

    if [ $type_now != $type_new ]; then
      semanage fcontext -a -t ${type_new} "${path}/.*"
      chcon -Rv -u system_u -t ${type_new} "${path}"
      echo 'Proper SELinux policies set'
    fi

  register: selinux_paths
  changed_when: selinux_paths.stdout.find('Proper SELinux policies set') != -1
  with_items:
    - path: data
      type: mongod_var_lib_t
    - path: log
      type: mongod_log_t
    - path: run
      type: mongod_var_run_t
