---
- name: Shutdown the server
  command: mongod --quiet --shutdown --dbpath "{{ dbpath_before }}"
  changed_when: false
  ignore_errors: true

- name: Stop the service
  systemd:
    name: mongod
    state: stopped

- name: Remove temporary files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ dbpath }}/run/mongod.pid"
    - "{{ dbpath }}/data/mongod.lock"

- name: Assure proper permissions
  file:
    path: "{{ dbpath }}/{{ item }}"
    recurse: true
    mode: 0755
    group: mongod
    owner: mongod
  with_items:
    - log
    - data
    - run
    - tmp

- name: Wait for a while
  pause:
    seconds: 5

- name: 'Get current config of MongoDB'
  command: cat /etc/mongod.conf
  changed_when: false
  register: current_config

- name: 'Set current dbpath'
  set_fact:
    port_now: "{{ (current_config.stdout | from_yaml)['net']['port'] }}"

- name: Start the service
  systemd:
    name: mongod
    state: started
    no_block: true

- name: Wait for it come up
  command: mongo --port '{{ port_now }}' --eval 'quit()'
  changed_when: false
  register: comeuppance
  until: comeuppance.rc == 0
  retries: 4
  delay: 5
