---
- name: Try to start the service
  service:
    name: mongod
    enabled: true
    state: restarted
  ignore_errors: true
  register: mongod_startup

- name: Try to recover
  when: mongod_startup.failed
  block:
    - name: Shutdown the server
      command: mongo admin --eval 'db.shutdownServer()'
      changed_when: false
      ignore_errors: true

    - name: Disable the service
      service:
        name: mongod
        enabled: false
        state: stopped

    - name: Assure proper permissions
      file:
        path: "{{ dbpath }}/{{ item }}"
        recurse: true
        mode: 0755
        group: mongod
        owner: mongod
      with_items:
        - log
        - data
        - run

    - name: Remove temporary files
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ dbpath }}/run/mongod.pid"
        - "{{ dbpath }}/data/mongod.lock"

    - name: Start again
      service:
        name: mongod
        enabled: true
        state: started
