---
- name: Test if the given root authentication data is valid
  command: mongo
  args:
    stdin: |
      use admin;
      if(!db.auth("{{ admin_username }}", "{{ admin_password }}")) {
        print("Falha na autenticação do root")
        quit(0);
      }
  register: root_auth_test
  changed_when: >-
    "Falha na autenticação do root" in root_auth_test.stdout

- name: Update root authentication
  when: root_auth_test is changed
  block:
    - name: Backup the current configuration
      slurp:
        src: /etc/mongod.conf
      register: original_conf

    - name: Stop mongod to enable the no-auth mode
      command: mongod-clean-shutdown

    - name: Copy the no-auth configuration
      template:
        src: no-auth.conf.j2
        dest: /etc/mongod.conf
        owner: mongod
        group: mongod
        mode: 0644

    - name: Start mongod in the no-auth mode
      command: mongod-clean-startup

    - name: Update root authentication data
      mongodb_user:
        database: admin
        user: "{{ admin_username }}"
        password: "{{ admin_password }}"
        roles:
          - root
        login_port: "{{ port_noauth }}"

    - name: Assert that the auth data is working
      command: mongo --port {{ port_noauth }}
      args:
        stdin: |
          use admin;
          if(!db.auth("{{ admin_username }}", "{{ admin_password }}")) {
            print("Falha na autenticação do root")
            quit(1);
          }

    - name: Stop mongod to disable the no-auth mode
      command: mongod-clean-shutdown

    - name: Copy back the original settings
      copy:
        content: "{{ original_conf.content | b64decode }}"
        dest: /etc/mongod.conf
        owner: mongod
        group: mongod
        mode: 0644

    - name: Start back up with the original configuration
      command: mongod-clean-startup

    - name: Assert again that the auth data is working
      command: mongo
      args:
        stdin: |
          use admin;
          if(!db.auth("{{ admin_username }}", "{{ admin_password }}")) {
            print("Falha na autenticação do root")
            quit(1);
          }
