---
- name: Generate a new keyfile
  set_fact:
    keyfile_content: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=700') }}"

- name: Grab current keyfile
  command: cat "{{ dbpath }}/config/replicaset.key"
  register: keyfile
  changed_when: false
  ignore_errors: true
  when: data_group in group_names
  run_once: true

- name: Provide the keyfile contents as a fact for all hosts
  set_fact:
    keyfile_content: "{{ hostvars[groups['primary'][0]].keyfile.stdout | trim }}"
  when: keyfile is not failed

- name: Copy it to all hosts
  copy:
    content: "{{ keyfile_content }}"
    dest: "{{ dbpath }}/config/replicaset.key"

- name: Assure proper permissions
  file:
    path: "{{ dbpath }}/config/replicaset.key"
    owner: mongod
    group: mongod
    mode: 0700
