---

- path: "{{ db_path }}"
  dir_mode: '700'
  file_mode: '600'
  se_type: mongod_var_lib_t
  changed: >
    {{ original_conf.storage.dbPath != db_path }}

- path: "{{ log_path }}"
  dir_mode: '600'
  file_mode: '600'
  se_type: mongod_log_t
  changed: >
    {{ (original_conf.systemLog.path | dirname) != log_path }}

- path: "{{ run_path }}"
  dir_mode: '644'
  file_mode: '644'
  se_type: mongod_var_run_t
  changed: >
    {{ (original_conf.processManagement.pidFilePath | dirname) != run_path }}

- path: "{{ config_path }}"
  dir_mode: '500'
  file_mode: '400'
  se_type: mongod_var_lib_t
  changed: true
